# Generated by Django 5.2.13 on 2026-04-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('nickname', models.CharField(max_length=64)),
                ('balance', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.CharField(max_length=64, unique=True)),
                ('train_id', models.CharField(max_length=128)),
                ('train_number', models.CharField(max_length=32)),
                ('train_route', models.CharField(blank=True, max_length=128)),
                ('predicted_delay', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('odds', models.FloatField(default=3.0)),
                ('station_code', models.CharField(blank=True, max_length=16)),
                ('data_partenza', models.CharField(blank=True, max_length=32)),
                ('scheduled_departure', models.BigIntegerField(default=0)),
                ('scheduled_arrival', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Attiva'), ('won', 'Vinta'), ('lost', 'Persa'), ('refunded', 'Rimborsata')], default='active', max_length=16)),
                ('actual_delay', models.IntegerField(blank=True, null=True)),
                ('win_amount', models.IntegerField(default=0)),
                ('placed_at', models.BigIntegerField()),
                ('resolved_at', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Scommessa',
                'verbose_name_plural': 'Scommesse',
                'ordering': ['-placed_at'],
            },
        ),
    ]
