# Generated by Django 5.2.13 on 2026-04-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_bonus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
