# Generated by Django 5.2.13 on 2026-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_last_daily_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=128)),
                ('train_number', models.CharField(blank=True, max_length=32)),
                ('day', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Treno d'Oro",
                'verbose_name_plural': "Treni d'Oro",
                'unique_together': {('train_id', 'day')},
            },
        ),
    ]
